name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

#    - name: Nexus Repo Publish
#      uses: sonatype-nexus-community/nexus-repo-github-action@master
#      with:
#        serverUrl: https://oss.sonatype.org/
#        username: ${{ secrets.NEXUS_USERNAME }}
#        password: ${{ secrets.NEXUS_PASSWORD }}
#        format: maven2
#        repository: maven-releases
#        coordinates: groupId=io.github.vlisianskii artifactId=expression-builder version=1.3
#        assets: extension=jar
#        filename: ./target/expression-builder-1.3-SNAPSHOT.jar

  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Scan
        run: mvn -B verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}